import Navbar from "@/components/Navbar";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const plus = Poppins({
  subsets: ["latin"],
  weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "EscColon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plus.className} antialiased`}
      >
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
