import { Plus_Jakarta_Sans } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";

const plus = Poppins({
  subsets: ["latin"],
  weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Life On Land",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plus.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
